source 'http://rubygems.org'

gem 'pry'

gem 'thin'
gem 'omniauth'
gem 'warden'
gem 'sinatra'
gem 'haml'
gem 'sass'
gem 'sprockets'
gem 'eco'

gem 'mysql2'
gem 'activerecord'
gem 'sinatra-activerecord'

gem 'therubyracer'
gem 'coffee-script'
