require File.join(File.dirname(__FILE__), 'client')
require File.join(File.dirname(__FILE__), 'clients')
require File.join(File.dirname(__FILE__), 'bot_manager')
require File.join(File.dirname(__FILE__), 'asynchronous_message_handler')
require File.join(File.dirname(__FILE__), 'message_factory_handler')
require File.join(File.dirname(__FILE__), 'interprocess_message')
